### ISSUE TITLE
Removing composer.phar

### ISSUE THREAD

**Issue by peter279k** [msalsas/itransformer#1]
As title, the `compoer.phar` should not be under Git version control.

This is the dependency package manager and it should let user download latest version by themselves when installing required dependencies.

**Comment by msalsas** [comment]
Hello @peter279k, thank you for your interest. I'm currently working on a big refactor, as this repository is 6 years old and it's the first thing I did when I was learning. I took a look recently and I saw a lot of bad practices and things that could be done much better, so I decided to make it from scratch with Symfony 4 but using some parts of the original. I've created a [new branch](https://github.com/msalsas/itransformer/tree/big-refactor) to do it. I would be very pleased if you also contribute. There's so much work to do yet. I would like it to be a good practices reference. Please, don't hesitate to contact me if you have any doubts. Thank you

**Comment by msalsas** [comment]
Hi @peter279k, I've already merged the refactor to master. There's still a lot to do though: increase coverage, improve frontend (not improved at all yet), improve dessign, etc. Feel free to collaborate if you want to. Thanks
