### ISSUE TITLE
Consider dropping php-5.x supports

### ISSUE THREAD

**Issue by peter279k** [msalsas/itransformer#2]
As title, the `php-7.x` has been released for the whiles.

I think it's time to drop `php-5.x` version supports.

IMHO, we can consider letting this platform require `php-7.2` version at least because this version is supported by official PHP team actively.

Once this issue is accepted, I'll be happy to work on this :).

**Comment by msalsas** [comment]
Totally agree. As I said [here](https://github.com/msalsas/itransformer/issues/1) there is a big refactor in progress where `php-5` is not supported. Let's work on it!
